### ISSUE TITLE
Fix: File upload breaks if there is a space after the count column label, i.e. "count "

### ISSUE THREAD

**Issue by milafrerichs** [OpenUpSA/wazimap-ng#151]
> File upload breaks if there is a space after the count column label, i.e. "count "

## Related issue:
https://trello.com/c/RGnQDHMq

**Comment by goyal1092** [comment]
@milafrerichs This issue will be fixed by PR: https://github.com/OpenUpSA/wazimap-ng/pull/133

Previously we didn't apply strip on headers while validating file data.
But I changed that in this PR : 
* For xls : https://github.com/OpenUpSA/wazimap-ng/pull/133/files#diff-43553be5440c752b4e4842580b6f110431fcd941d5f1d5a8565a8c862840e93bR78
* For csv : https://github.com/OpenUpSA/wazimap-ng/pull/133/files#diff-7820bbdb2e74e2bedd3b8cccccbcd2e567ef56d1ce29ba696689dd99a59701ceR78
